export enum FieldType {
  CheckboxGroup = 'checkbox_group',
  RadioGroup = 'radio_group',
  Select = 'select',
  MultiSelect = 'multiple_select',
  OpinionScale = 'opinion_scale',
  Rating = 'rating',
  Text = 'text',
  Textarea = 'textarea',
  Email = 'email',
  Number = 'number',
  Phone = 'phone',
  Regex = 'regex',
  Website = 'website',
}
